import type { Opdracht, Monteur } from './types';

export const monteur: Monteur = {
  id: 'm1',
  naam: 'Jan Bakker',
  voornaam: 'Jan',
  email: 'jan@eurowheelz.nl',
  busCapaciteit: 8,
  vanHuis: true,
};

export const opdrachtenVandaag: Opdracht[] = [
  {
    id: 'OP-1055',
    type: 'onderhoud',
    status: 'ingepland',
    locatie: 'Strandhotel Scheveningen',
    adres: 'Gevers Deynootplein 30',
    postcode: '2586 CK',
    stad: 'Scheveningen',
    datum: '2025-04-16',
    prioriteit: 3,
    urgent: false,
    deadline: null,
    notitie: 'Toegang via zij-ingang. Vraag naar Lisa bij receptie.',
    voertuigen: [
      { kenteken: 'EW-0001-A', kleur: '#E63946' },
      { kenteken: 'EW-0001-B', kleur: '#2A9D8F' },
      { kenteken: 'EW-0001-C', kleur: '#264653' },
      { kenteken: 'EW-0001-D', kleur: '#E9C46A' },
      { kenteken: 'EW-0001-E', kleur: '#F4A261' },
      { kenteken: 'EW-0001-F', kleur: '#E63946' },
      { kenteken: 'EW-0001-G', kleur: '#2A9D8F' },
      { kenteken: 'EW-0001-H', kleur: '#264653' },
    ],
    contactpersoon: 'Lisa de Groot',
    telefoon: '+31 6 1234 5678',
    routeVolgorde: 1,
  },
  {
    id: 'OP-1061',
    type: 'reparatie',
    status: 'ingepland',
    locatie: 'Vakantiepark De Koog',
    adres: 'Rommelpot 8',
    postcode: '1796 AZ',
    stad: 'De Koog',
    datum: '2025-04-16',
    prioriteit: 2,
    urgent: true,
    deadline: '2025-04-18',
    notitie: 'EW-0002-C heeft kapot achterlicht na valpartij. Klant heeft ook een scheurende zitting gemeld.',
    voertuigen: [
      { kenteken: 'EW-0002-C', kleur: '#E63946' },
    ],
    contactpersoon: 'Mark Visser',
    telefoon: '+31 6 8765 4321',
    routeVolgorde: 2,
  },
  {
    id: 'OP-1064',
    type: 'accu',
    status: 'ingepland',
    locatie: 'Hotelpark Julianadorp',
    adres: 'Zandweg 22',
    postcode: '1787 PK',
    stad: 'Julianadorp',
    datum: '2025-04-16',
    prioriteit: 3,
    urgent: false,
    deadline: null,
    notitie: 'Upgrade van 8× 20Ah naar 6× 30Ah. Oude accu\'s meenemen terug naar loods.',
    voertuigen: [],
    contactpersoon: 'Petra van Dam',
    telefoon: '+31 6 5555 1234',
    routeVolgorde: 3,
  },
  {
    id: 'OP-1063',
    type: 'pechhulp',
    status: 'ingepland',
    locatie: 'Camping Les Dunes',
    adres: 'Duinweg 4',
    postcode: '8670',
    stad: 'Koksijde (BE)',
    datum: '2025-04-16',
    prioriteit: 1,
    urgent: true,
    deadline: null,
    notitie: 'Twee gestrande gasten. Sleutel ophalen op camping.',
    voertuigen: [],
    contactpersoon: 'Camping reception',
    telefoon: '+32 58 123 456',
    routeVolgorde: 4,
    sleutelOphalen: true,
    pechStops: [
      {
        id: 'ps1',
        adres: 'Duinpad 12, Koksijde',
        coördinaten: { lat: 51.1023, lng: 2.6497 },
        pechType: 'lege_accu',
        notitie: 'Gast staat bij het pad richting zee.',
        kenteken: null,
        gevonden: null,
      },
      {
        id: 'ps2',
        adres: 'Strandboulevard 88, Koksijde',
        coördinaten: { lat: 51.0989, lng: 2.6521 },
        pechType: 'lekke_band',
        notitie: 'Gast staat bij het strandhuis.',
        kenteken: null,
        gevonden: null,
      },
    ],
  },
];

export const opdrachtenWeek: Record<string, Opdracht[]> = {
  '2025-04-14': [
    {
      id: 'OP-1042',
      type: 'onderhoud',
      status: 'uitgevoerd',
      locatie: 'Park Zandvoort',
      adres: 'Strandweg 1',
      postcode: '2041 JA',
      stad: 'Zandvoort',
      datum: '2025-04-14',
      prioriteit: 3,
      urgent: false,
      deadline: null,
      notitie: '',
      voertuigen: [
        { kenteken: 'ZV-001', kleur: '#345022' },
        { kenteken: 'ZV-002', kleur: '#F3A713' },
        { kenteken: 'ZV-003', kleur: '#E63946' },
      ],
      contactpersoon: 'Henk Jansen',
      telefoon: '+31 6 1111 2222',
      routeVolgorde: 1,
    },
  ],
  '2025-04-15': [
    {
      id: 'OP-1048',
      type: 'reparatie',
      status: 'uitgevoerd',
      locatie: 'Hotel Katwijk',
      adres: 'Prins Hendrikweg 10',
      postcode: '2225 TL',
      stad: 'Katwijk',
      datum: '2025-04-15',
      prioriteit: 2,
      urgent: false,
      deadline: null,
      notitie: '',
      voertuigen: [
        { kenteken: 'KW-041', kleur: '#2A9D8F' },
      ],
      contactpersoon: 'Inge Peters',
      telefoon: '+31 6 9876 5432',
      routeVolgorde: 1,
    },
  ],
  '2025-04-16': opdrachtenVandaag,
  '2025-04-17': [
    {
      id: 'OP-1070',
      type: 'plaatsen',
      status: 'ingepland',
      locatie: 'Camping Texel',
      adres: 'Rommelpot 12',
      postcode: '1791 NE',
      stad: 'Den Burg, Texel',
      datum: '2025-04-17',
      prioriteit: 3,
      urgent: false,
      deadline: null,
      notitie: '5 nieuwe e-choppers uit loods.',
      voertuigen: [
        { kenteken: 'TX-101', kleur: '#345022' },
        { kenteken: 'TX-102', kleur: '#345022' },
        { kenteken: 'TX-103', kleur: '#345022' },
        { kenteken: 'TX-104', kleur: '#345022' },
        { kenteken: 'TX-105', kleur: '#345022' },
      ],
      contactpersoon: 'Boele de Vries',
      telefoon: '+31 6 4444 3333',
      routeVolgorde: 1,
    },
  ],
};
